# Generated by Django 2.1.7 on 2019-03-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_auto_20190318_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
