# Generated by Django 2.1.7 on 2019-04-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_art_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='sd_type',
            field=models.CharField(choices=[('CreativeWork', 'CreativeWork'), ('Book', 'Book'), ('ComicStory', 'ComicStory'), ('DigitalDocument', 'DigitalDocument'), ('Drawing', 'Drawing'), ('Game', 'Game'), ('Manuscript', 'Manuscript'), ('Map', 'Map'), ('MediaObject', 'MediaObject'), ('Movie', 'Movie'), ('MusicComposition', 'MusicComposition'), ('MusicRecording', 'MusicRecording'), ('Painting', 'Painting'), ('Photograph', 'Photograph'), ('Play', 'Play'), ('Poster', 'Poster'), ('Sculpture', 'Sculpture'), ('ShortStory', 'ShortStory'), ('SoftwareApplication', 'SoftwareApplication'), ('Thesis', 'Thesis'), ('VisualArtwork', 'VisualArtwork'), ('WebPage', 'WebPage')], default='VisualArtwork', max_length=19),
        ),
    ]
