# Generated by Django 2.1.7 on 2019-09-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0026_historicalevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
