# Generated by Django 2.1.7 on 2019-02-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190227_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
