# Generated by Django 2.1.7 on 2019-02-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190227_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='event',
            new_name='venue',
        ),
    ]
