# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20190303_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpage',
            name='project',
            field=models.ForeignKey( on_delete= models.SET_NULL, blank=True, null=True, to='events.ProjectPage'),
            preserve_default=False,
        ),
    ]
