# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_artpage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpage',
            name='events',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, to='events.EventPage'),
        ),
        migrations.AlterField(
            model_name='artpage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.ProjectPage'),
        ),
    ]
