# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 19:59
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20190304_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpage',
            name='project',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art', to='events.ProjectPage'),
        ),
    ]
