# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 02:44
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20190305_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpage',
            name='events',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, to='events.EventPage'),
        ),
    ]
