# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20190305_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpage',
            name='events',
        ),
    ]
