# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_artpage_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
