# Generated by Django 2.1.7 on 2019-03-07 15:18

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_auto_20190306_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpage',
            name='project',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=None, related_name='art', to='events.ProjectPage'),
        ),
    ]
