# Generated by Django 2.1.7 on 2019-03-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('events', '0036_auto_20190307_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='artindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='artindexpage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='artpage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='artpage',
            name='events',
        ),
        migrations.RemoveField(
            model_name='artpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='artpage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='artpage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='artpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='artpagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='artpagegalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='artpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='artpagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='projectindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='projectindexpage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='projectpagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projectpagegalleryimage',
            name='page',
        ),
        migrations.DeleteModel(
            name='ArtCategory',
        ),
        migrations.DeleteModel(
            name='ArtIndexPage',
        ),
        migrations.DeleteModel(
            name='ArtPage',
        ),
        migrations.DeleteModel(
            name='ArtPageGalleryImage',
        ),
        migrations.DeleteModel(
            name='ArtPageTag',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='ProjectIndexPage',
        ),
        migrations.DeleteModel(
            name='ProjectPage',
        ),
        migrations.DeleteModel(
            name='ProjectPageGalleryImage',
        ),
    ]
