# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_auto_20190306_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='access_token_key',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='access_token_secret',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='consumer_key',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='consumer_secret',
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter_access_token_key',
            field=models.CharField(default='', help_text='Your Twitter access_token_key', max_length=255, verbose_name='access token key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter_access_token_secret',
            field=models.CharField(default='', help_text='Your Twitter access_token_secret', max_length=255, verbose_name='access token secret'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter_consumer_key',
            field=models.CharField(default='', help_text='Your Twitter consumer_key', max_length=255, verbose_name='consumer key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter_consumer_secret',
            field=models.CharField(default='', help_text='Your Twitter consumer_secret', max_length=255, verbose_name='consumer secret'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram_password',
            field=models.CharField(help_text='Your Instagram username, without the @', max_length=255, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram_username',
            field=models.CharField(help_text='Your Instagram username, without the @', max_length=255, verbose_name='user name'),
        ),
    ]
