# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 16:23
from __future__ import unicode_literals

from django.db import migrations
import django_crypto_fields.fields.encrypted_text_field


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_auto_20190306_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='test',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=71),
        ),
    ]
