# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 16:41
from __future__ import unicode_literals

from django.db import migrations
import django_crypto_fields.fields.encrypted_char_field


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_socialmediasettings_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='test',
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram_password',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text='Your Instagram username, without the @ (Encryption: RSA local)', max_length=214, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter_access_token_secret',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text='Your Twitter access_token_secret (Encryption: RSA local)', max_length=214, verbose_name='access token secret'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter_consumer_secret',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text='Your Twitter consumer_secret (Encryption: RSA local)', max_length=214, verbose_name='consumer secret'),
        ),
    ]
