# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0006_auto_20190306_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('block', models.BooleanField(default=False)),
                ('service', models.CharField(choices=[('Ig', 'Instagram'), ('Tw', 'Twitter')], max_length=2)),
                ('target', models.CharField(choices=[('Gr', 'Greece'), ('Eu', 'Europe'), ('Ny', 'New York'), ('La', 'Los Angeles')], default='Ny', max_length=2)),
                ('caption', models.CharField(max_length=255)),
            ],
        ),
    ]
