# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0007_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='facebookaccount',
            name='account_ptr',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='account_ptr',
        ),
        migrations.RemoveField(
            model_name='pintrestaccount',
            name='account_ptr',
        ),
        migrations.RemoveField(
            model_name='twitteraccount',
            name='account_ptr',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='FacebookAccount',
        ),
        migrations.DeleteModel(
            name='InstagramAccount',
        ),
        migrations.DeleteModel(
            name='PintrestAccount',
        ),
        migrations.DeleteModel(
            name='TwitterAccount',
        ),
    ]
