# Generated by Django 2.1.7 on 2019-03-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_auto_20190318_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='visible',
            new_name='is_visible',
        ),
    ]
