# Generated by Django 2.1.7 on 2019-03-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_auto_20190318_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_project_tags',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tagulous_project_tags',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='art',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Tagulous_Project_tags',
        ),
    ]
