# Generated by Django 2.1.7 on 2019-03-17 16:51

import autoslug.fields
from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='get_slug')),
                ('media', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='entities', to='archive.Media')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
