# Generated by Django 2.1.7 on 2019-03-17 17:34

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20190317_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
