# Generated by Django 2.1.7 on 2019-03-18 20:00

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_auto_20190318_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name_plural': 'art'},
        ),
        migrations.AddField(
            model_name='art',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='archive.Project'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', to='archive.Tagulous_Entity_tags', tree=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', to='archive.Tagulous_Project_tags', tree=True),
        ),
    ]
