# Generated by Django 2.1.7 on 2019-04-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_art_sd_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='year',
            field=models.PositiveSmallIntegerField(default=2018),
        ),
    ]
