# Generated by Django 2.1.7 on 2019-05-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_auto_20190405_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='author',
            new_name='authors',
        ),
    ]
