# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 15:54
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_artpage_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpage',
            name='events',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='events.EventPage'),
        ),
    ]
