# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20190303_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpage',
            name='project',
        ),
    ]
