# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('events', '0022_auto_20190304_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindexpage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage', verbose_name='Search image'),
        ),
    ]
