# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 01:55
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20190305_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='events.ArtCategory'),
        ),
    ]
