# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 02:45
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20190305_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpage',
            name='events',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, to='events.EventPage'),
        ),
    ]
