# Generated by Django 2.1.7 on 2019-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='details',
        ),
        migrations.RemoveField(
            model_name='event',
            name='started_date',
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='css',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
