# Generated by Django 2.1.7 on 2019-02-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20190219_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='started_date',
            field=models.SmallIntegerField(),
        ),
    ]
