# Generated by Django 2.1.7 on 2019-02-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_project_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster_for', to='work.Art'),
        ),
    ]
