# Generated by Django 2.1.7 on 2019-02-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20190219_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.Art'),
        ),
    ]
