# Generated by Django 2.1.7 on 2019-02-19 20:49

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20190219_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='started_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='get_slug'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='get_slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='get_slug'),
        ),
    ]
