# Generated by Django 2.1.7 on 2019-02-19 21:02

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_auto_20190219_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='get_slug')),
                ('order', models.IntegerField()),
                ('template', models.CharField(default='page.html', max_length=128)),
                ('description_155', models.TextField(blank=True, default='')),
                ('description_200', models.TextField(blank=True, default='')),
                ('description_300', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='')),
                ('in_menubar', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, default='')),
                ('css', models.TextField(default='')),
                ('javascript', models.TextField(default='')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
