# Generated by Django 2.1.7 on 2019-02-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='javascript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
