# Generated by Django 2.1.7 on 2019-02-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_auto_20190219_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='css',
            field=models.TextField(blank=True, default=''),
        ),
    ]
