# Generated by Django 2.1.7 on 2019-02-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_auto_20190219_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='leader',
            field=models.TextField(blank=True, default=''),
        ),
    ]
