# Generated by Django 2.1.7 on 2019-02-21 16:49

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_event_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Art_gendre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_art_gendre',
            unique_together={('slug',)},
        ),
        migrations.AddField(
            model_name='art',
            name='gendre',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, blank=True, initial='Sculpture, Painting, Video, Performance', null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Tagulous_Art_gendre'),
        ),
    ]
