# Generated by Django 2.1.7 on 2019-02-21 17:46

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_auto_20190221_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='gendre',
        ),
        migrations.AddField(
            model_name='art',
            name='gendre',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='Painting, Performance, Sculpture, Video', max_count=5, to='work.Tagulous_Art_gendre'),
        ),
    ]
