# Generated by Django 2.1.7 on 2019-02-21 20:00

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_auto_20190221_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='hobbies',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='hobbies',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='hobbies',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='page',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='work.views.hobbies_autocomplete', force_lowercase=True, help_text='Enter a comma-separated tag string', initial='food/eating, food/cooking, gaming/football', to='work.Tags', tree=True),
        ),
    ]
