# Generated by Django 2.1.7 on 2019-02-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0019_auto_20190221_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='event',
            name='header',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
