# Generated by Django 2.1.7 on 2019-02-23 14:57

import autoslug.fields
from django.db import migrations, models
import versatileimagefield.fields
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_auto_20190221_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='caption')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=work.models.image_path)),
            ],
        ),
    ]
