# Generated by Django 2.1.7 on 2019-02-23 15:03

from django.db import migrations, models
import sortedm2m.fields
import versatileimagefield.fields
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0022_auto_20190223_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='album',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='albums', to='work.Media'),
        ),
        migrations.AddField(
            model_name='art',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=work.models.image_path),
        ),
    ]
