# Generated by Django 2.1.7 on 2019-02-23 15:19
import pprint
import os
from django.db import migrations
from django.core.files.base import ContentFile

def migrate_images_to_media(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Media = apps.get_model('work', 'Media')
    Image = apps.get_model('work', 'Image')
    for image in Image.objects.all():
        caption = image.art.title
        image_file =  ContentFile(image.image.read())
        image_file.name = 'art/lydia-venieri-{}{}'.format(
            image.art.slug,
            os.path.splitext(image.image.name)[1]
        )

        media = Media.objects.create(
                image=image_file,
                caption=caption,
            )

        #    name='{} - {}{}'.format(participant.name, photo.title, ('(%d)' % i) if i else ''),
        pprint.pprint( media )
        # image_file.name = 'lydia-venieri-{}-{}-{}-{}{}{}'.format(
        #     festivalproject.festival.slug,
        #     festivalproject.project.slug,
        #     photo.artist.slug,
        #     photo.slug,
        #     ('-%d' % i) if i else '',
        #     os.path.splitext(photo.photo.name)[1]
        # )
        # media, created = Media.objects.get_or_create(
        #         name='{} - {}{}'.format(participant.name, photo.title, ('(%d)' % i) if i else ''),
        #         defaults=dict(
        #             image=image,
        #             text=(photo.description + '\n\n' + photo.text).strip(),
        #         )
        # )


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_auto_20190223_1503'),
    ]

    operations = [
        migrations.RunPython(migrate_images_to_media, reverse_code=migrations.RunPython.noop),
    ]
