# Generated by Django 2.1.7 on 2019-02-23 16:29

from django.db import migrations
import versatileimagefield.fields
import work.models





class Migration(migrations.Migration):



    dependencies = [
        ('work', '0024_auto_20190223_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=work.models.media_path),
        ),
    ]
