# Generated by Django 2.1.7 on 2019-02-23 18:12

import autoslug.fields
from django.db import migrations, models
import sortedm2m.fields
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0025_auto_20190223_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='get_slug')),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('media', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='album', to='work.Media')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='work.views.hobbies_autocomplete', force_lowercase=True, help_text='Enter a comma-separated tag string', initial='food/eating, food/cooking, gaming/football', to='work.Tags', tree=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
