# Generated by Django 2.1.7 on 2019-02-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0027_auto_20190223_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='album',
        ),
    ]
