# Generated by Django 2.1.7 on 2019-02-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0029_remove_art_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
