# Generated by Django 2.1.7 on 2019-02-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0031_auto_20190223_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
