# Generated by Django 2.1.7 on 2019-02-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0032_auto_20190223_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='poster',
        ),
    ]
