# Generated by Django 2.1.7 on 2019-02-23 18:32

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0033_remove_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='work.views.hobbies_autocomplete', force_lowercase=True, help_text='Enter a comma-separated tag string', initial='food/eating, food/cooking, gaming/football', to='work.Tags', tree=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='work.views.hobbies_autocomplete', force_lowercase=True, help_text='Enter a comma-separated tag string', initial='food/eating, food/cooking, gaming/football', to='work.Tags', tree=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='work.views.hobbies_autocomplete', force_lowercase=True, help_text='Enter a comma-separated tag string', initial='food/eating, food/cooking, gaming/football', to='work.Tags', tree=True),
        ),
    ]
