# Generated by Django 2.1.7 on 2019-02-24 01:43
import datetime
import pprint
from django.db import migrations

group_shows = """2017|  Summer Sex I - On the Spur of the Moment|Lichtundfire|New York
2017|On Paper|Paris Koh Fine Arts|New York
2017|Xanadu:Land of Enchantment|President’s Gallery John Jay College of Criminal Justice CUNY|New York|Curated by Dr. Thalia Vrachopoulos
2016|Collateral Damage|The Anya and Andrew Shiva Gallery|New York|Curated by Drs. Jungsil Lee & Thalia Vrachopoulos
2015|Ithaca Returned|The Blender Gallery|Athens
2015|Mykonos Biennale - Antidote Treasure Hunt|Delos|Greece
2015|Mykonos Biennale|Archaeologic Museum|Mykonos
2015|EYES ONLY: PHOTOGRAPHS|Stux + Haller|NEW YORK
2014|THE STOLEN BIRD|Vanessa Quang|Paris
2014|MYKONOS BIENNALE|CRISIS AND PAGANISM|Vanessa Quang|Paris
2014|BURNING BRIGHT: TIGER|TIGER|Stux Gallery|New York
2013|Mykonos Biennale|Archaeologic Museum|Mykonos.
2013|HELL AS PAVILION|Palais de Tokyo|Paris|curated by Nadja Argyropoulou 
2013|In Praise of Chance and Failure|Family Business|New York
2010| Sculptures in the Garden| Botanical Gardens of Kefalonia, Kosmtatos Foundation|Greece|curated by Liana Scourles.
2010|Low Blow: And Other Species of Confusion|Stefan Stux Gallery|New York
2009|Tokyo 101 Contemporary|Terra Gallery|Tokyo
2008| Scope 08|Terra Gallery|Miami
2008|Scope 08|Terra Gallery|London
2008|Art Taipei|Terra Gallery|Taiwan
2008|Korean International Art Fair|Terra Gallery|Korea
2008|Art Miami 08|Stux Gallery|Miami
2008|Shanghai Art Fair|Terra Gallery|China
2008|Selection Art Moscow 2008|Terra Gallery|Moscow
2008|From Head to Toe|Stux Gallery|New York
2008|NEXT Art Fair|Stux Gallery|Chicago
2007|Macedonian Museum of Contemporary Art|Thessaloniki|Greece
2007|War Games|Gallery Quang, Show Off!|Paris
2007|Scope Basel International Art Fair|Stux Gallery|Basel
2007|Art Athina|Luxe Gallery|Athens
2007|Art Chicago|Luxe Gallery|Chicago
2007|Art Miami|Stux Gallery|Miami
2007|The Nightly News|Luxe|New York|curated by Kathleen Goncharov and Stephan Stoyanov
2006|War Games|Gallery Luxe FIAC 2006|Paris
2006|Tarot|Gallery Quang|Paris
2006|The Last Conflict|Location One|New York
2006|The Venieri Tarot|Gallery Quang|Paris
2006|Oh, You Beautiful Doll|Andrea Meislin Gallery|New York|curated by Douglas F.Maxwell
2005|ARTISSIMA 12|Luxe Gallery|Turin
2005|Platonic Exodus - FIAC 2005|Luxe Gallery|Paris
2005|It’s Not About Sex|Luxe Gallery|New York
2005|Propos d’Europe IV|Foundation Hippocrene, Agence de Rob Mallet- Stevens|Paris
2005|Art Athina|Luxe Gallery|Athens
2005|Flash Art Fair|Luxe Gallery|Milan
2005|Diva|Luxe Gallery|New York
2004|Drawings|Luxe Gallery|New York 
2004|FIAC 2004|Gallery Luxe|Paris 
2004|Art in General|Studio Visit|New York
2004|Tower of Symbols|Summer Olympics|Athens
2003|Alive In New York|Eugenia Cucalon Gallery|New York
2003|Centre Culturel Hellenique|Paris|France
2002|Lydia Venieri|Atelier Mallet Stevens|Paris
2002|FIAC 2002|Video Novella|Gallerie Samy Kinge|Paris
2002|Lydia Venieri|Centre Cultural de Marrousi|Athens
2001|Storm On Moon|Selini Gallery|Athens
2001|Greek Gods and Heroes|Centre for Contemporary Art in Dordrecht|Netherlands
2000|Greek Contemporary Art|Glassing Gallery|Munster, Germany
2000|L’Oeil De La Galerie “Samy Kinge”|Selini Galerie|Athens
1999|A Water Melon| BenetonCinema Phiri|Athens
1999|Pret Art Porter|Dakis Ioannou Fondation|Athens
1999|Approaching Hellinism: Generation 80s & 90s|Cultural Centre|Stockholm
1999|Approaching Hellinism: Generation 80s & 90s|Dazarma Museum|Falum, Sweden
1999|Touch of Art in Ordinary Objects|Selini Gallery|Athens
1999|Opening of Possibilities|Hewlett Packard|Gazi,Athens
1999|Approaching Hellinism: Generation 80s & 90s|Vaiden Castle|Luxembourg
1999|Art Quake|Benakiom Museum|Athens
1999|Approaching Hellinism: Generation 80s & 90s|National Gallery of Greece|Athens
1998|Triptych|Downtown Gallery|Athens
1998|Art & Technology Festival|Eleana Tounta Gallery|Athens
1998|Trash Art|Gazi|Athens
1998|Croix Rouge||Athens
1998|Flying Art|Municipality of Athens, Varvakio Square|Athens
1997|42nd Salon de Montrouge|Salon de Montrouge|Paris
1996|Manifesta 1|Rotterdam|Netherlands
1996|Pandora’s Box, Women/Beyond Borders|California and Basel|Switzerland
1995|International Video Art Festival|Syracuse|Italy
1995|FIAC 1995, “Fin”|Gallerie Samy Kinge|Paris
1995|Lydia Venieri|Espace EIFFEL Branely|Paris
1994|Premiere Rencontre Internationale de Sculpture|Centre Culturel Europeen de Delphes|Delphes,Greece
1992|Ermata. Errance du Sacre|Galerie Montenay|Paris
1992|Spira I. Douze Createurs Grecs|Circulo de Bellas Artes|Madrid
1992|Metamorphoses du Moderne|Pinacotheque Nationale|Athens
1990|Biennale Internationale de Jeunes Createurs|Musee Skirnion|Athens
1989|Espirt et Corps|sous les auspices du Ministere de la Culture Greece|Zappion Athens
1989|Celebration de la Terre|organisation par Earth Trust, Centre Culturel du Parc de la Liberte|Athens
1989|Humour et Revolution|organisee a l’occation de 200 ans de la Revolution Franciase|Biennale de Cannes|Cannes et Barcelone
1988|Image et Lettre|Galerie Niki Diana Marquardt|Paris| Curated by Demosthenes Davetas.
1988|Salon de Montrouge|Paris|France
1988|Exposition de l’Institue Francais d’Athenes|Salle Costis Palamas|Athens
1987|Exposition Panhellenique|Piree|Greece
1987|Carte Blanche, a l’occation de l’anniversaire de 10 ans du Centre George Pompidou|Galeries Contemporaines|Paris 
1986| Paris Salon des Comparaisons|Grande Palais|Paris
1986| Biennale de Jeunes Createurs de la Mediterannee Europeenne||Greece
1986|Europeenne|Thessalonique|Greece
1985|Salon de Mai|Grande Palais|Paris
1983|Exposition a l’Ateilier de Yankel|Galeire Bernanos|Paris"""


def import_group_shows(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Event = apps.get_model('work', 'Event')
    for line in group_shows.split('\n'):
        print(line)
        parts = line.split('|')
        if len(parts) == 5:
            year, title, venue, location, info = parts
        else:
            year, title, venue, location = parts
            info=''
        pprint.pprint((year, title, venue, location, info))
        # continue
        e = Event(
            title=title.strip(),
            date=datetime.date(int(year), 1, 1),
            order=1,
            tags=['show/group'],
            venue=venue.strip(),
            slug='{}-{}'.format(title.strip(), int(year)),
            location=location.strip())
        e.save()
        pprint.pprint((
            title.strip(),
            e)
           )

class Migration(migrations.Migration):

    dependencies = [
        ('work', '0035_auto_20190224_0056'),
    ]

    operations = [
        migrations.RunPython(import_group_shows, reverse_code=migrations.RunPython.noop),
    ]
