# Generated by Django 2.1.7 on 2019-02-24 23:29

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('work', '0036_auto_20190224_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='media',
            field=gm2m.fields.GM2MField('work.Album', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
        migrations.AddField(
            model_name='event',
            name='media',
            field=gm2m.fields.GM2MField('work.Album', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
        migrations.AddField(
            model_name='project',
            name='media',
            field=gm2m.fields.GM2MField('work.Album', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
    ]
