# Generated by Django 2.1.7 on 2019-02-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0037_auto_20190224_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='media',
        ),
        migrations.RemoveField(
            model_name='event',
            name='media',
        ),
        migrations.RemoveField(
            model_name='project',
            name='media',
        ),
    ]
