# Generated by Django 2.1.7 on 2019-02-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0038_auto_20190224_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='poster',
        ),
    ]
